name: Release (Changesets)
on:
  push:
    branches: [main]
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          scope: '@identityofsine'
          always-auth: true
          cache: npm
      - run: npm ci
      - name: Prepare publish script
        run: |
          chmod +x .github/scripts/publish-if-needed.mjs || true
      - uses: changesets/action@v1
        with:
          publish: node .github/scripts/publish-if-needed.mjs
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Provide both variables; setup-node writes .npmrc expecting NODE_AUTH_TOKEN
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}


